### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by husin151** [staticshreyas/Attendance-Portal#3]
I tried your application and sent OTP code for verification but there is this error

Error: Invalid login: 534-5.7.9 Application-specific password required. Learn more at
534 5.7.9 https://support.google.com/mail/?p=InvalidSecondFactor l63-20020a638842000000b003f61c311e79sm7603846pgd.56 - gsmtp
    at SMTPConnection._formatError (D:\campus\TA\absen-portal\node_modules\nodemailer\lib\smtp-connection\index.js:774:19)
    at SMTPConnection._actionAUTHComplete (D:\campus\TA\absen-portal\node_modules\nodemailer\lib\smtp-connection\index.js:1513:34)
    at SMTPConnection.<anonymous> (D:\campus\TA\absen-portal\node_modules\nodemailer\lib\smtp-connection\index.js:540:26)
    at SMTPConnection._processResponse (D:\campus\TA\absen-portal\node_modules\nodemailer\lib\smtp-connection\index.js:932:20)
    at SMTPConnection._onData (D:\campus\TA\absen-portal\node_modules\nodemailer\lib\smtp-connection\index.js:739:14)
    at TLSSocket.SMTPConnection._onSocketData (D:\campus\TA\absen-portal\node_modules\nodemailer\lib\smtp-connection\index.js:189:44)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internals/streams/readable.js:293:12)
    at readableAddChunk(internal/streams/readable.js:267:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:206:10)
    at TLSWrap.onStreamRead(internal/stream_base_commons.js:188:23) {
  code: 'EAUTH',
  response: '534-5.7.9 Application-specific password required. Learn more at\n' +
    '534 5.7.9 https://support.google.com/mail/?p=InvalidSecondFactor l63-20020a638842000000b003f61c311e79sm7603846pgd.56 - gsmtp',
  responseCode:534,
  command: 'AUTH PLAIN'

**Comment by blacklovertech** [comment]
https://myaccount.google.com/lesssecureapps open on Gmail and enable it. 

will work  tried !!
